name: "Commit changes and Raise PR"
description: "Commit changes to branch and raise PR"

inputs:
  github-token:
    description: 'GitHub token for creating pull requests'
    required: true
    default: ${{ github.token }}

runs:
  using: composite
  steps:
  # Pull update from git, switch to branch
  - name: checkout update branch
    shell: bash
    run: git fetch && git switch ${{ env.COMMIT_BRANCH }}

  # create a draft pull request, this is because, by a github design, workflows can not trigger
  # other workflows, unless a PAT, SSH ect is used to trigger, which isn't done here, yet.
  # So to trigger workflow, just push draft to ready.
  - name: Create Pull Request
    shell: bash
    run: |
      PR_BODY="This PR updates the Ruby version to $TARGET_RUBY_VERSION.

      Changes made:
      - Updated .ruby-version file
      - Updated Gemfile ruby version
      - Updated Dockerfile ruby version
      - Rebuilt Gemfile.lock dependencies

      Please review and test before merging."

      gh pr create \
        --title "Update Ruby to version $TARGET_RUBY_VERSION" \
        --body "$PR_BODY" \
        --base master \
        --head $COMMIT_BRANCH \
        --draft

    env:
      GH_TOKEN: ${{ inputs.github-token }}
      #GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #    steps:
      #      - uses: actions/checkout@v4
      #      - uses: andrew/ruby-upgrade-action@main
      #        with:
      #          github-token: ${{ secrets.GITHUB_TOKEN }}
