name: "Setup branch"
description: "Create branch for Ruby updates and setup Ruby Eng"

outputs:
  COMMIT_BRANCH:
    description: 'Branch to commit changes to'
    value: ${{steps.set-branch-name.outputs.COMMIT_BRANCH}}

runs:
  using: composite
  steps:
  - name: set branch name
    id: set-branch-name
    shell: bash
    run: |
      echo "COMMIT_BRANCH=update-to-ruby-${{ env.TARGET_RUBY_VERSION }}" >> $GITHUB_OUTPUT

  - name: Create or checkout branch
    shell: bash
    run: |
      if git ls-remote --exit-code --heads origin " ${{ steps.set-branch-name.COMMIT_BRANCH }}"; then
        echo "branch already exists ${{ steps.set-branch-name.outputs.COMMIT_BRANCH }}"
      else
        git branch ${{ steps.set-branch-name.outputs.COMMIT_BRANCH }}
        git push -u origin  HEAD
      fi
