name: "Setup branch"
description: "Create branch for Ruby updates and setup Ruby Eng"

runs:
  using: composite
  steps:
  - name: set branch name
    id: set-branch-name
    shell: bash
    run: |
      echo "COMMIT_BRANCH=update-to-ruby-${{ env.TARGET_RUBY_VERSION }}" >> $GITHUB_ENV

  - name: Create or checkout branch
    shell: bash
    run: |
      if git ls-remote --exit-code --heads origin " ${{ env.COMMIT_BRANCH }}"; then
        git checkout ${{ env.COMMIT_BRANCH }}
      else
        git checkout -b ${{ env.COMMIT_BRANCH }}
      fi
