name: "Setup branch"
description: "Create branch for Ruby updates and setup Ruby Eng"

runs:
  using: composite
  steps:
  - name: set branch name
    id: set-branch-name
    shell: bash
    run: |
      echo "BRANCH_NAME=update-to-ruby-${{ env.TARGET_RUBY_VERSION }}" >> "$GITHUB_ENV"
      echo "COMMIT_BRANCH=env.BRANCH_NAME" >> "$GITHUB_OUTPUt"

  - name: Create or checkout branch
    shell: bash
    run: |
      if git ls-remote --exit-code --heads origin " ${{ env.BRANCH_NAM }}"; then
        git checkout ${{ env.BRANCH_NAME }}
      else
        git checkout -b ${{ env.BRANCH_NAME }}
      fi
