name: Upgrade Ruby

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * 0" # Runs Monthly

jobs:
  upgrade-ruby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: update-ruby.yml@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}