name: Update Ruby

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * 0" # Runs Monthly

jobs:
  check-ruby-setup:
    runs-on: ubuntu-latest
    outputs:
      TARGET_RUBY_VERSION: ${{ steps.check-ruby.outputs.TARGET_RUBY_VERSION }}
      NEW_RUBY: ${{ steps.check-ruby.outputs.NEW_RUBY }}
      COMMIT_BRANCH: ${{ steps.setup-branch.outputs.COMMIT_BRANCH }}
      RUBY_PATHS: ${{ steps.check-ruby.outputs.RUBY_PATHS }}
    steps:

    - name: Check out code
      uses: actions/checkout@v4
      with:
        ref: add_GH_Action_upddate_Ruby

    - name: Check Ruby Version
      id: check-ruby
      uses: ./.github/actions/check-ruby

    - name: Setup github branch for Ruby Updates
      id: setup-branch
      if: ${{ steps.check-ruby.outputs.NEW_RUBY }} == 'true'
      uses: ./.github/actions/setup-branch
      env:
        TARGET_RUBY_VERSION: ${{ steps.check-ruby.outputs.TARGET_RUBY_VERSION }}

  upgrade-ruby:
    runs-on: ubuntu-latest
    needs: [check-ruby-setup]
    steps:

    - name: Check out code
      uses: actions/checkout@v4
      with:
        ref: add_GH_Action_upddate_Ruby

    -  name: Update Ruby Version
       env:
         TARGET_RUBY_VERSION: ${{ needs.check-ruby-setup.outputs.TARGET_RUBY_VERSION }}
         COMMIT_BRANCH: ${{ needs.check-ruby-setup.outputs.COMMIT_BRANCH }}
         NEW_RUBY: ${{ needs.check-ruby-setup.outputs.NEW_RUBY}}
         RUBY_PATHS: ${{ needs.check-ruby-setup.outputs.RUBY_PATHS}}
       ## Only update if the Ruby Version has changed.
       if: ${{ env.NEW_RUBY }} == 'true'
       uses: ./.github/actions/update-ruby

    - name: Commit and Raise PR
      env:
         TARGET_RUBY_VERSION: ${{ needs.check-ruby-setup.outputs.TARGET_RUBY_VERSION }}
         COMMIT_BRANCH: ${{ needs.check-ruby-setup.outputs.COMMIT_BRANCH }}
         NEW_RUBY: ${{ needs.check-ruby-setup.outputs.NEW_RUBY}}
      uses: ./.github/actions/commit-changes
      ## Only update if the Ruby Version has changed.
      if: ${{ env.NEW_RUBY }} == 'true'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}