name: Update Ruby

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * 0" # Runs Monthly

jobs:
  upgrade-ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Check Ruby Version
        uses: ./.github/actions/check-ruby
      - name: Update Ruby Version
        uses: ./.github/actions/update-ruby
      - name: Raise PR
        uses: ./.github/actions/commit-changes
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}