name: Update Ruby

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * 0" # Runs Monthly

env:
    TARGET_RUBY_VERSION: ''
    RUBY_UPDATED: 'false'
    COMMIT_BRANCH: ''

jobs:
  check-ruby:
    runs-on: ubuntu-latest
#    outputs:
#      TARGET_RUBY_VERSION: ${{ steps.check-ruby.outputs.TARGET_RUBY_VERSION }}
#      RUBY_UPDATED: ${{ steps.check-ruby.outputs.RUBY_UPDATED }}
#      COMMIT_BRANCH: ${{ steps.check-ruby.outputs.COMMIT_BRANCH }}
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        ref: add_GH_Action_upddate_Ruby
    - name: Check Ruby Version
      id: check-ruby
      uses: ./.github/actions/check-ruby
    - name: Setup github branch for Ruby Updates
      id: setup-branch
      if: ${{ env.RUBY_UPDATED }} == 'true'
      uses: ./.github/actions/setup-branch

  upgrade-ruby:
    runs-on: ubuntu-latest
    needs: [check-ruby]
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        ref: add_GH_Action_upddate_Ruby

    -  name: Update Ruby Version
#       env:
#         TARGET_RUBY_VERSION: ${{ needs.check-ruby.outputs.TARGET_RUBY_VERSION }}
#         COMMIT_BRANCH: ${{ needs.check-ruby.outputs.COMMIT_BRANCH }}
       if: ${{ env.RUBY_UPDATED }} == 'true'
       uses: ./.github/actions/update-ruby
       with:
          ruby-path: '.'

  commit-changes:
    runs-on: ubuntu-latest
    needs: [check-ruby, upgrade-ruby]
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        ref: add_GH_Action_upddate_Ruby

    - name: Raise PR
#      env:
#         TARGET_RUBY_VERSION: ${{ needs.check-ruby.outputs.TARGET_RUBY_VERSION }}
#         COMMIT_BRANCH: ${{ needs.check-ruby.outputs.COMMIT_BRANCH }}
      uses: ./.github/actions/commit-changes
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}